const initialState = {
  id: null,
  userId: null,
  expertPanel: null,
  sex: null,
  birthYear: null,
  height: null,
  weight: null,
  practiceType: null,
  clubCity: null,
  clubName: null,
  startOfPracticeYear: null,
  shoeSize: null,
  skateWidth: null,
  shinGardSize: null,
  pantSize: null,
  elbowPadSize: null,
  shoulderPadSize: null,
  gloveSize: null,
  helmetSize: null,
  headSize: null,
};
